In [188]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [189]:
matches_df = pd.read_csv('Dataset/matches.csv')
match_details = pd.read_csv('Dataset/deliveries.csv')

In [190]:
# taking a fraction of data due to its large size
matches_df = matches_df[:195]
match_details = match_details[:100273]

In [191]:
matches_df.head()

,id,year,date,winner,result,win_by_runs,win_by_wickets,player_of_match,team1,team2,toss_winner,toss_decision,umpire1,umpire2,venue
0,1,2017,2017-01-13,Australia,normal,92.0,NaN,MS Wade,Australia,Pakistan,Australia,bat,MD Martell,C Shamshuddin,"Brisbane Cricket Ground, Woolloongabba"
1,2,2017,2017-01-15,Pakistan,normal,NaN,6.0,Mohammad Hafeez,Australia,Pakistan,Australia,bat,CB Gaffaney,P Wilson,Melbourne Cricket Ground
2,3,2017,2017-01-19,Australia,normal,NaN,7.0,SPD Smith,Australia,Pakistan,Australia,field,SD Fry,C Shamshuddin,Western Australia Cricket Association Ground
3,4,2017,2017-01-22,Australia,normal,86.0,NaN,DA Warner,Australia,Pakistan,Australia,bat,CB Gaffaney,MD Martell,Sydney Cricket Ground
4,5,2017,2017-01-26,Australia,normal,57.0,NaN,DA Warner,Australia,Pakistan,Australia,bat,SD Fry,C Shamshuddin,Adelaide Oval

In [192]:
match_details.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,wide_runs,bye_runs,legbye_runs,noball_runs,batsman_runs,extra_runs,total,player_dismissed,dismissal_kind,fielder
0,1,1,Australia,Pakistan,1,1,DA Warner,TM Head,Mohammad Amir,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Australia,Pakistan,1,2,DA Warner,TM Head,Mohammad Amir,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Australia,Pakistan,1,3,DA Warner,TM Head,Mohammad Amir,0,0,0,0,0,0,0,NaN,NaN,NaN
3,1,1,Australia,Pakistan,1,4,DA Warner,TM Head,Mohammad Amir,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Australia,Pakistan,1,5,DA Warner,TM Head,Mohammad Amir,1,0,0,0,0,1,1,NaN,NaN,NaN

In [193]:
len(match_details)

100273

In [100]:
count=0
for i in range(len(match_details)):
    if  match_details.iloc[i]['wide_runs']!=0 or match_details.iloc[i]['noball_runs']!=0:
        count+=1
v=count/len(match_details)
print("Estimation of wide/no ball = {}".format(v))

Estimation of wide/no ball = 0.025011718009833154

### We got our Wide/No ball probability  v = 0.0250
![123](images/4.jpg)

# 100272 194

In [194]:
print("Total Matches:{}".format(len(matches_df)))
print("total Teams: {}".format(len(set(matches_df.team1))))
print("Total number of Batsmen: {}".format(len(set(match_details.batsman))))
print("Total number of Bowlers: {}".format(len(set(match_details.bowler))))
print("Estimation of wide/no ball = {}".format(v))
print("Total balls Bowled: {}".format(len(match_details)))

Total Matches:195
total Teams: 15
Total number of Batsmen: 528
Total number of Bowlers: 386
Estimation of wide/no ball = 0.025011718009833154
Total balls Bowled: 100273

In [195]:
# feature engineering
drop_col_list = ['non_striker','wide_runs', 'bye_runs',
       'legbye_runs', 'noball_runs', 'batsman_runs', 'extra_runs','dismissal_kind', 'fielder']
match_details = match_details.drop(drop_col_list,axis=1)
match_details.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,bowler,total,player_dismissed
0,1,1,Australia,Pakistan,1,1,DA Warner,Mohammad Amir,0,NaN
1,1,1,Australia,Pakistan,1,2,DA Warner,Mohammad Amir,0,NaN
2,1,1,Australia,Pakistan,1,3,DA Warner,Mohammad Amir,0,NaN
3,1,1,Australia,Pakistan,1,4,DA Warner,Mohammad Amir,0,NaN
4,1,1,Australia,Pakistan,1,5,DA Warner,Mohammad Amir,1,NaN

In [196]:
# Calculating the Score for each ball
Score=[]
total_run = 0
temp=1
for i,runs in enumerate(match_details.total):
    if temp != match_details.iloc[i]["inning"]:
        total_run=0
        temp = match_details.iloc[i]["inning"]
    total_run += runs
    Score.append(total_run)
print(len(Score))

100273

In [197]:
# Check Is out or not
is_wicket=[]
out=0
for i,wicket in enumerate(match_details.player_dismissed):
    if  pd.isnull(wicket) == False:
        out=1
    else:
        out=0
    is_wicket.append(out)
len(is_wicket)

100273

In [198]:
#Calculation for Wickets taken
Wickets=[]
total_wickets=0
temp=1
for i,wicket in enumerate(match_details.player_dismissed):
    if  pd.isnull(wicket) == False:
        total_wickets+=1
    if temp != match_details.iloc[i]["inning"]:
            total_wickets=0
            temp = match_details.iloc[i]["inning"]
    Wickets.append(total_wickets)
print(len(Wickets))

100273

In [199]:
#Calculation for Balls_Bowled
Balls_Bowled=[]
total_balls=0
temp=1
for i,ball in enumerate(match_details.ball):
    if ball <=6:
        if temp != match_details.iloc[i]["inning"]:
            total_balls=0
            temp = match_details.iloc[i]["inning"]
        total_balls+=1
    Balls_Bowled.append(total_balls)
len(Balls_Bowled)

100273

In [200]:
### Adding the new features into the dataset
match_details.rename(columns = {'total':'runs_accquired'}, inplace = True)
match_details = match_details.drop('player_dismissed',axis=1)
match_details['Score'] = Score
match_details['Wickets'] = Wickets
match_details['Balls_Bowled'] = Balls_Bowled
match_details['Is_OUT'] = is_wicket

In [201]:
match_details.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'bowler', 'runs_accquired', 'Score', 'Wickets',
       'Balls_Bowled', 'Is_OUT'],
      dtype='object')

In [202]:
match_details = match_details[['match_id', 'inning', 'batting_team', 'bowling_team', 'over','Balls_Bowled','ball','batsman', 'bowler', 'runs_accquired', 'Score', 'Wickets','Is_OUT']]

### Now our dataset has all the feature to predict the outcome
![as](images/3.jpg)

In [203]:
match_details.head()

,match_id,inning,batting_team,bowling_team,over,Balls_Bowled,ball,batsman,bowler,runs_accquired,Score,Wickets,Is_OUT
0,1,1,Australia,Pakistan,1,1,1,DA Warner,Mohammad Amir,0,0,0,0
1,1,1,Australia,Pakistan,1,2,2,DA Warner,Mohammad Amir,0,0,0,0
2,1,1,Australia,Pakistan,1,3,3,DA Warner,Mohammad Amir,0,0,0,0
3,1,1,Australia,Pakistan,1,4,4,DA Warner,Mohammad Amir,0,0,0,0
4,1,1,Australia,Pakistan,1,5,5,DA Warner,Mohammad Amir,1,1,0,0

In [204]:
# Label Encoding of categorical values
from sklearn import preprocessing
le_team = preprocessing.LabelEncoder()
le_batsman = preprocessing.LabelEncoder()
le_bowler = preprocessing.LabelEncoder()

match_details.batting_team = le_team.fit_transform(match_details.batting_team)
match_details.bowling_team = le_team.fit_transform(match_details.bowling_team)
match_details.batsman = le_batsman.fit_transform(match_details.batsman)
match_details.bowler = le_batsman.fit_transform(match_details.bowler)

In [205]:
# After Label Encoding
match_details.head()

,match_id,inning,batting_team,bowling_team,over,Balls_Bowled,ball,batsman,bowler,runs_accquired,Score,Wickets,Is_OUT
0,1,1,1,8,1,1,1,114,239,0,0,0,0
1,1,1,1,8,1,2,2,114,239,0,0,0,0
2,1,1,1,8,1,3,3,114,239,0,0,0,0
3,1,1,1,8,1,4,4,114,239,0,0,0,0
4,1,1,1,8,1,5,5,114,239,1,1,0,0

### At this point our features are ready, time to add the target variable in our dataset

![abc](images/2.jpg)

In [206]:
Target_var = []
target =0
for i in range(len(match_details)):
    if match_details.iloc[i]['Is_OUT']==1:
        target = 1
    elif match_details.iloc[i]['runs_accquired']==0:
        target = 2
    elif match_details.iloc[i]['runs_accquired']==1:
        target = 3
    elif match_details.iloc[i]['runs_accquired']==2:
        target = 4
    elif match_details.iloc[i]['runs_accquired']==3:
        target = 5
    elif match_details.iloc[i]['runs_accquired']==4:
        target = 6
    elif match_details.iloc[i]['runs_accquired']==6:
        target = 7
    Target_var.append(target)
len(Target_var)

100273

In [207]:
match_details['Target'] = Target_var

In [208]:
match_details.head()

,match_id,inning,batting_team,bowling_team,over,Balls_Bowled,ball,batsman,bowler,runs_accquired,Score,Wickets,Is_OUT,Target
0,1,1,1,8,1,1,1,114,239,0,0,0,0,2
1,1,1,1,8,1,2,2,114,239,0,0,0,0,2
2,1,1,1,8,1,3,3,114,239,0,0,0,0,2
3,1,1,1,8,1,4,4,114,239,0,0,0,0,2
4,1,1,1,8,1,5,5,114,239,1,1,0,0,3

## Checkpoint:

In [209]:
match_details.to_csv('Processed_dataset.csv',index=False)

## Finally our dataset is ready for modeling

* In modeling , Given some features we will generate the outcome using the equation below:
![asx](images/5.jpg)
* But to get the result of Eq 3 we need another equation given below:
![ada](images/6.jpg)
* We can get unknown parameters for equation 6 from below:
![qwe](images/7.jpg)
* In short:
![wrte](images/8.jpg)

In [398]:
# generating the unkown parameters before the distributions
del_1 = np.random.uniform()
del_2 = np.random.uniform()

tow = np.random.gamma(1.0,1.0)
sigma = np.random.gamma(1.0,1.0)

u_i = (tow**2)*np.random.randn(528) #batsman
u_j = (tow**2)*np.random.randn(386) #bowler

![234](images/11.jpg)

In [399]:
def generate_alk():
    alk = []
    for i in range(9):
        ak=[]
        for j in range(6):
            if len(ak)==0:
                ak.append(np.random.randn())
            else:
                temp = np.random.randn()
                while(ak[-1]>temp):
                    temp= np.random.randn()
                ak.append(temp)
        alk.append(ak)
    return alk

In [400]:
a_lk = generate_alk()
a_lk = np.array(a_lk)
a_lk = (sigma**2)*a_lk

In [401]:
a_lk

array([[-0.62892396,  0.23881564,  1.00242203,  1.42205023,  1.55806653,
         1.71149593],
       [ 0.81407072,  0.9408261 ,  1.08219004,  1.15414047,  1.20558939,
         1.60984593],
       [ 0.53582691,  0.75133601,  0.96270398,  0.98028865,  1.28692581,
         1.95290497],
       [ 0.42817781,  0.51970156,  1.27341475,  1.40966968,  1.43030072,
         1.4551182 ],
       [-0.50016836, -0.39491516,  0.4152678 ,  0.53365398,  0.89078499,
         1.17615392],
       [ 0.61208451,  0.78137341,  1.36403914,  1.3685419 ,  1.38758707,
         1.5421192 ],
       [ 0.27957286,  0.55268545,  2.02965436,  2.34074399,  2.39608686,
         2.6944311 ],
       [ 0.45911305,  0.90716723,  1.19455916,  1.37018114,  1.43402154,
         1.43989578],
       [ 0.49930394,  0.85086306,  0.87713535,  1.01640984,  1.09255721,
         1.29955012]])

## implementing the situation
![rrg](images/9.jpg)

In [361]:
def Situation(over,wicket_loss):
    if 1<=over<=15 and 0<=wicket_loss<=3:
        return 1
    if 16<=over<=35 and 0<=wicket_loss<=3:
        return 2
    if 36<=over<=50 and 0<=wicket_loss<=3:
        return 3
    if 1<=over<=15 and 4<=wicket_loss<=6:
        return 4
    if 16<=over<=35 and 4<=wicket_loss<=6:
        return 5
    if 36<=over<=50 and 4<=wicket_loss<=6:
        return 6
    if 1<=over<=15 and 7<=wicket_loss<=9:
        return 7
    if 16<=over<=35 and 7<=wicket_loss<=9:
        return 8
    elif 36<=over<=50 and 7<=wicket_loss<=9:
        return 9

![ada](images/6.jpg)
![ada1](images/10.jpg)

In [440]:
def Predicted_P_ijwbk(i,j,k,l):
    new_del = 0
    if l <=3:
        new_del=0
    elif 3<l<=6:
        new_del=del_1
    elif 6<l<=9:
        new_del=del_1+del_2
    
    #print(term1,term2)
    if k==1 or k==7:
        result = 0.01
    else:
        term1 = a_lk[l-1][k-1] -u_i[i] - new_del + u_j[j]
        term2 = a_lk[l-1][k-2] -u_i[i] - new_del + u_j[j]
        result = np.random.logistic(term1) - np.random.logistic(term2)
    return result

## So, We Finally got Our... Prob(Xb=k)
![asx](images/5.jpg)

In [ ]:
#### Check Predicted_P_ijwbk(i,j,k,l) for 1 and 7

![rf](images/12.jpg)

In [368]:
match_details.Target.value_counts()

2    50886
3    32760
6     7603
4     4736
1     2699
7     1114
5      475
Name: Target, dtype: int64

In [371]:
target_freq = np.array([2699,50886,32760,4736,475,7603,1114])/len(match_details)

In [387]:
## Testing out algorithm on a Match
match1 = match_details[match_details.match_id == 1]
match1_1st = match1[match1.inning==1]

In [388]:
match1_1st

,match_id,inning,batting_team,bowling_team,over,Balls_Bowled,ball,batsman,bowler,runs_accquired,Score,Wickets,Is_OUT,Target
0,1,1,1,8,1,1,1,114,239,0,0,0,0,2
1,1,1,1,8,1,2,2,114,239,0,0,0,0,2
2,1,1,1,8,1,3,3,114,239,0,0,0,0,2
3,1,1,1,8,1,4,4,114,239,0,0,0,0,2
4,1,1,1,8,1,5,5,114,239,1,1,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,1,1,1,8,50,296,2,324,130,4,265,9,0,6
306,1,1,1,8,50,297,3,324,130,0,265,9,0,2
307,1,1,1,8,50,298,4,324,130,0,265,9,0,2
308,1,1,1,8,50,299,5,324,130,2,267,9,0,4
309,1,1,1,8,50,300,6,324,130,1,268,9,0,3

### Observation on the data
* Australia is the batting in the 1st innings
* Pakisthan is bowling
* Opening Batsmen are DA Warner and TM Head
* 1st Bowler is Mohammad Amir

### Important Insight
There are **310 rows** in this dataset, A one innings have only **300 balls(50 overs)**<br>
So, **the extra 10 balls must be wide or no balls**<br>

In [389]:
# Overall Overview of the match
matches_df.iloc[0]

id                                                      1
year                                                 2017
date                                           2017-01-13
winner                                          Australia
result                                             normal
win_by_runs                                            92
win_by_wickets                                        NaN
player_of_match                                   MS Wade
team1                                           Australia
team2                                            Pakistan
toss_winner                                     Australia
toss_decision                                         bat
umpire1                                        MD Martell
umpire2                                     C Shamshuddin
venue              Brisbane Cricket Ground, Woolloongabba
Name: 0, dtype: object

## Algorithm:
<img src="images/13.jpg" width="600" height="600">

In [391]:
print(v)
print(target_freq)

0.025011718009833154
[0.02691652 0.50747459 0.32670809 0.04723106 0.00473707 0.075823
 0.01110967]

In [441]:
for dat in range(len(match1_1st)):
    u = np.random.uniform()
    if u < v:
        print("WideB:")
        print(target_freq[1],target_freq[2],target_freq[3],target_freq[4],target_freq[5],target_freq[6])
    else:
        #Xb
        l = Situation(match1_1st.iloc[dat]["over"],match1_1st.iloc[dat]["Wickets"])
        i = match1_1st.iloc[dat]["batsman"]
        j = match1_1st.iloc[dat]["bowler"]
        print("Ball:")
        print(Predicted_P_ijwbk(i,j,1,l),Predicted_P_ijwbk(i,j,2,l),Predicted_P_ijwbk(i,j,3,l),Predicted_P_ijwbk(i,j,4,l),Predicted_P_ijwbk(i,j,5,l),Predicted_P_ijwbk(i,j,6,l),Predicted_P_ijwbk(i,j,7,l))

Ball:
0.01 4.982648025909615 2.0420068023891234 5.143634820783334 0.7872143514374512 1.5477267809963098 0.01
Ball:
0.01 1.6489461221173578 2.665596189948687 2.442079545534938 0.07120214217815546 6.543550206418116 0.01
Ball:
0.01 4.183974335334525 1.8121347387448161 2.5103679584102525 2.6276111598926013 0.22635432463680472 0.01
Ball:
0.01 1.4544984271368575 0.004116632815325705 1.2572673395990663 1.4187997565976525 5.550568058787835 0.01
Ball:
0.01 0.4463941720264587 4.031924711026291 1.1893383042524985 1.4365849207501666 8.15381304582418 0.01
Ball:
0.01 0.9098254401141228 2.4445162456872875 0.45750312632468404 1.1039149504308563 2.618609391999944 0.01
Ball:
0.01 3.240846356466096 2.826738695874408 0.33032636192149867 0.44165863908044445 1.1788355776864758 0.01
Ball:
0.01 0.4109036901116463 1.454659544568177 1.3433772431258828 0.2996701265173103 1.2522341351025679 0.01
Ball:
0.01 1.5854532127536445 2.9082315882331216 3.821561437676861 2.8391349144383047 1.0299789697430919 0.01
Ball:
0.01 1.566159334714564 0.6632843446596598 1.2638813656532137 0.05474448502681306 2.207070066040245 0.01
Ball:
0.01 1.4579138072200402 3.7923173039377858 1.419379118537106 1.9330625145307068 3.96853654376022 0.01
Ball:
0.01 1.5156149752942463 3.2034672490915277 4.4225098317756615 2.3179218052261614 1.5519973509378842 0.01
Ball:
0.01 3.6212094741149095 0.7808810311459781 0.5670802538149693 3.0044646958374557 2.063856153154539 0.01
Ball:
0.01 6.446658407417198 0.28198522667891424 0.47058329172073354 5.598678213459211 3.2395017300530657 0.01
Ball:
0.01 0.9349549333320311 2.711833856517558 2.737557112965889 4.668036217030758 2.3041191003889496 0.01
Ball:
0.01 1.4975751414918248 1.2839992744305493 0.24859507720848795 3.877681666108627 1.3543400281420697 0.01
Ball:
0.01 2.902392748407031 1.612046599845975 1.849791618469891 0.49212063584982224 0.19344167254373856 0.01
Ball:
0.01 0.19274323884461705 0.43448853899276485 0.9318406122531679 2.46597125680078 0.41024660633696053 0.01
Ball:
0.01 0.0950379883422442 0.365598474847455 4.124957518905807 0.9219978408106209 2.5759868778409825 0.01
Ball:
0.01 3.590936344721386 0.4374518678939442 1.0001212496826253 0.5558533816679117 0.9798009679055002 0.01
Ball:
0.01 1.5199577793531929 2.8657539860688996 1.2761825019263715 0.5775166314585025 2.6794028523424096 0.01
Ball:
0.01 0.8972758992794615 3.152042412308699 1.854256301124131 2.698950849362931 1.018457673782083 0.01
Ball:
0.01 4.32288058596889 1.2226394446642512 1.5879963820123226 1.6504079655741093 1.4615471062661198 0.01
Ball:
0.01 3.1671664285147005 1.097280542963754 0.4242024101729178 0.9685029514825196 0.7993155140666675 0.01
Ball:
0.01 1.5081556612436595 2.8256349511157035 0.2800855930524424 0.33405866670857254 0.1587985780767065 0.01
Ball:
0.01 3.298093661438001 2.25491897216924 0.8587879534235561 1.5412667556434878 2.8116999495104062 0.01
Ball:
0.01 0.7557562242370213 3.94241927435265 0.47115058513497776 2.3553322047626617 1.6829251422692915 0.01
Ball:
0.01 3.026624431554302 1.040976834552973 2.5327663120675954 1.3440652204261325 1.9476633339314757 0.01
Ball:
0.01 1.2522238978559388 0.25879796742556804 0.30519424093755987 1.5201204046964756 1.6025871372566771 0.01
Ball:
0.01 1.353538085775213 1.8991700726485299 0.4406487745180723 0.9764757711797252 2.3410719617823235 0.01
Ball:
0.01 3.7044532363910747 0.5017402588715435 3.6785599077160827 3.2525642791434617 0.7324409299496306 0.01
Ball:
0.01 0.09258322091106752 0.385602934992902 4.955174645333285 0.3616509058070494 2.4022883907046935 0.01
Ball:
0.01 5.059388227807183 4.0940122915868 0.4090450965783785 0.2362800664497522 0.18298045162409515 0.01
Ball:
0.01 2.4744464300815965 1.9055169463327064 1.6977394761739408 2.725818776657441 3.2649778189190624 0.01
Ball:
0.01 0.9210689234695926 5.341330561360216 0.7720209453541005 0.6419951807032316 2.968808069375904 0.01
Ball:
0.01 0.9085434859941437 0.09917224309749162 0.5995932781509612 2.105639174586244 0.17211359030921702 0.01
Ball:
0.01 2.70657576776032 1.1665452852799156 3.1608696054920946 0.3759195396670827 4.676441516323669 0.01
Ball:
0.01 1.1849332896763323 6.20993200380831 1.9740221278554484 1.0718297519993878 0.39909760086121615 0.01
Ball:
0.01 0.8636820369711612 1.9746381624727014 3.46704836970905 2.171753710773465 0.6533042648230944 0.01
Ball:
0.01 3.6043808825464083 1.9020611786302961 2.1019651976749847 1.5347399559450257 0.37161037930564245 0.01
Ball:
0.01 0.23849092104402558 3.378264000297138 0.20471414344778682 0.7081588118901738 1.826357956869007 0.01
Ball:
0.01 2.311876368632687 0.9070489324603159 1.1318108990686588 6.085242922631488 0.6476604036338782 0.01
Ball:
0.01 0.4569726264360373 2.6200696772727756 0.3299046211715714 1.7461494294392128 3.3444409464373717 0.01
Ball:
0.01 0.07028466849505971 0.572854126193246 1.285356496295893 2.4513426797036435 1.296191811626302 0.01
Ball:
0.01 0.5458641324920994 0.957037552553397 2.024898263955676 0.8750174354291516 0.1700911121286337 0.01
Ball:
0.01 5.165309456800417 4.48197238765231 0.2924231712359755 0.2773842197651508 0.6771518757116086 0.01
Ball:
0.01 0.19231074735692144 1.5644285260191817 1.4696926636070882 1.8111603937001068 0.7166429949704536 0.01
Ball:
0.01 1.1597496697267524 1.423102463394203 1.382110878676881 1.495812622407461 1.3836040680940616 0.01
Ball:
0.01 6.23739748280865 1.1853166841482352 0.6521268583549462 2.709616478967612 2.0747977039577314 0.01
Ball:
0.01 1.510968994184162 0.4466961052734033 2.3130408706943193 1.4900735798492426 0.991706199158034 0.01
Ball:
0.01 0.8152493048534937 0.6838294916249541 1.13021137572643 0.052242398741889406 2.3453532984608834 0.01
Ball:
0.01 1.2621242065319358 0.024499277336544556 0.5328300162583002 1.5547289213014204 0.6571760024321949 0.01
Ball:
0.01 1.450635050276812 2.783222451732046 4.399133278487722 1.2779075734602219 5.396830479974866 0.01
Ball:
0.01 1.7612204205844137 0.25651051492136206 0.7721418346419345 0.40917166294566165 1.4163986441674483 0.01
Ball:
0.01 2.867093537363236 0.9760553572559277 2.9152468861564618 1.7507818824346515 0.2578899175858993 0.01
Ball:
0.01 3.423863621619063 2.401153146958941 1.2190297263608194 1.1205756633556399 1.6064490756966334 0.01
Ball:
0.01 8.010541851743183 0.5080676086907601 1.6684506900377074 1.2053289926080282 2.493210789944042 0.01
Ball:
0.01 2.3576453155340733 1.7817688813802435 1.6122009272498619 3.906194442998243 1.881495565236371 0.01
Ball:
0.01 0.5617883714535947 0.13803661586797777 0.5975692456777129 5.261223263971491 1.5079894024423743 0.01
Ball:
0.01 0.11465296944835535 0.48309088519358767 0.2788014996513595 0.45255118705063246 4.4814589382115875 0.01
Ball:
0.01 1.011459307447377 4.072241630746547 4.009400673568746 0.7685214959168527 0.779694021798937 0.01
Ball:
0.01 4.972594709057208 1.250660915049466 2.0122157571187236 2.327828119602229 1.4280669929284162 0.01
WideB:
0.5074745943574043 0.32670808692270104 0.047231059208361174 0.004737067804892643 0.07582300320126056 0.011109670599264009
Ball:
0.01 6.888477904189857 1.6095365057487259 2.1853802532512563 1.4556209027823928 0.24063896141611107 0.01
Ball:
0.01 1.9496360172157408 1.043947052705783 2.319996346368041 0.29653980386906753 1.0801341342153967 0.01
Ball:
0.01 5.1533624143417525 1.1550079465077816 0.005017614142117766 3.240955026630759 0.7473610670539828 0.01
Ball:
0.01 0.4361117376509244 0.9969972055963472 0.7562480359631252 0.2565647521340524 1.697955287325954 0.01
Ball:
0.01 4.628328051690879 2.048582698685717 1.0169966587608181 2.6361143989150624 0.23557082005129737 0.01
Ball:
0.01 0.8194411010111866 7.118206376109718 1.1164339483795178 6.100058698090042 0.22698187433599593 0.01
Ball:
0.01 2.1657129844634184 2.9243416002720015 1.9232606200322215 1.0584154814021014 1.0144975394926163 0.01
Ball:
0.01 0.42849970793188596 1.2482498902717452 2.872509894951741 0.32757258344958484 3.872060479447202 0.01
Ball:
0.01 0.12868777661270248 0.6408277159225241 0.5843804738844278 0.885219211174725 3.3029609146850754 0.01
Ball:
0.01 1.6271407290353412 1.0378551604664439 0.5430701409069854 3.6158168918503932 3.813872756866335 0.01
Ball:
0.01 2.410517378280957 1.4279549024331977 2.65244008454541 1.7207253521366244 1.4676544738954975 0.01
WideB:
0.5074745943574043 0.32670808692270104 0.047231059208361174 0.004737067804892643 0.07582300320126056 0.011109670599264009
Ball:
0.01 2.3426620796123974 4.023681972555436 0.20201437345892737 1.255481837959245 0.6184709088449081 0.01
Ball:
0.01 1.5642288853227195 4.883381468950361 3.757726423649961 4.021740089381536 2.9083334186744016 0.01
Ball:
0.01 5.443429665011105 0.1928565791031983 0.948904146404185 3.3218856002652553 0.26021306312016246 0.01
Ball:
0.01 0.7945204654647018 1.2724964547366877 0.17447560829651598 1.022594232033345 1.0902838588771677 0.01
Ball:
0.01 3.6439358976284772 0.3759844984210725 1.9093091012402783 0.648201771089137 0.02726914214054288 0.01
Ball:
0.01 2.6799727251573184 6.356890109323153 4.3159937915308895 0.02714993929989329 2.364099015947303 0.01
Ball:
0.01 1.9411442099045182 1.8907892314396657 2.004040211814529 0.2736044980850716 1.2312233793759912 0.01
Ball:
0.01 3.793265924837561 0.5379839268434901 2.6172203559457707 1.5648545406847447 4.33093227112867 0.01
Ball:
0.01 0.5007808673426333 2.2424527052445957 0.03806509689330406 2.0789158788834463 0.10998487723806682 0.01
Ball:
0.01 4.2342779718942705 0.6988978003356396 0.9439689951252714 1.9791644315930914 0.798245913568643 0.01
Ball:
0.01 0.8503221972058622 0.3800010421367456 0.09755695685775656 2.464469179196899 1.4950968340512472 0.01
Ball:
0.01 0.179357192494461 0.0037664319423187376 2.792252763122675 4.0982381398707455 1.4920790017452261 0.01
Ball:
0.01 0.1107692050358502 0.9789577672610275 0.8748403550153481 0.9766088145863683 0.7193977458061557 0.01
Ball:
0.01 2.952764172878514 0.4210605976615616 0.4073749392969511 0.8452224666896777 2.5602625350774755 0.01
Ball:
0.01 4.754408959898898 4.758852184008424 1.5550492574490937 0.8249058146111876 1.820780042352244 0.01
Ball:
0.01 3.0477840269033463 5.057856982752982 2.6031935754945676 0.0263703021440711 3.677862442400893 0.01
Ball:
0.01 1.1714422719938338 0.04330036735627843 0.3527691010865138 0.46577176758327254 5.795368960188925 0.01
Ball:
0.01 2.027960603370409 2.2135580624754447 0.04187176114386415 5.119502087990033 1.2905090502032286 0.01
Ball:
0.01 1.0651624473818675 8.305295818435365 0.2711560198050085 2.588688479126601 0.8464215732806035 0.01
Ball:
0.01 1.570923759880063 2.58751082876705 1.7075952052165406 1.9981457458606164 2.8791743354309 0.01
Ball:
0.01 0.49149323518107013 0.1812694741597507 4.111556814462809 1.1348641846027308 0.3834647956593267 0.01
Ball:
0.01 3.37696203885156 1.230642371892055 5.135050860536222 0.6342344645259876 3.0600459933631527 0.01
Ball:
0.01 0.41453463694698867 0.9193644082114689 0.14127204992217934 0.9834506208847866 2.0472261980912747 0.01
Ball:
0.01 1.0839256927007606 3.1418987047791225 1.1575270325160876 2.760822994861489 1.057721187875947 0.01
Ball:
0.01 0.5151428126363693 3.997695917902492 2.77613768782219 1.4808119422155088 4.0326408998416445 0.01
Ball:
0.01 1.3198237933948578 3.008032052435182 1.5714374844068537 0.988676326197643 2.5110607255537927 0.01
Ball:
0.01 2.6115541414412924 2.5380275953006715 0.6133289840189999 0.4167283697263533 6.518653399132756 0.01
Ball:
0.01 1.802387915434664 0.19012965988062847 2.044002723981814 0.9110269669938755 2.1248090515173614 0.01
Ball:
0.01 0.4169567111764074 3.1305388663869373 5.605792403214199 0.33266744239020424 3.496485030736534 0.01
Ball:
0.01 1.9129673262407305 5.075429403798713 0.2566191342003923 0.9732253040548137 0.7991200254544447 0.01
Ball:
0.01 0.7188077740656207 8.32992755114704 1.513482685526425 0.2905677539362095 1.207026788493855 0.01
Ball:
0.01 2.0796869294027047 2.6706662571852036 0.7308906688006012 0.9269752462000931 3.748127145987039 0.01
Ball:
0.01 1.3289748138761732 1.6139589902276983 6.62803549032577 3.70354827639059 2.576428198981061 0.01
Ball:
0.01 1.210107387027318 1.9902354585469642 1.2317061497227575 0.38258011808335785 2.9987139266250686 0.01
Ball:
0.01 2.0898523117853074 1.064543987290131 2.2858846695498003 4.9298766720847595 1.6474920697573214 0.01
Ball:
0.01 1.811538095272064 0.7673977021598304 2.08161207498381 2.9072277951518783 2.2284301992279003 0.01
Ball:
0.01 3.654848624082846 2.191276045139854 2.3294158450714497 1.8243005520601074 0.20679577067936505 0.01
Ball:
0.01 1.942487360716688 6.21666516626383 3.0564072978971772 4.528754002565438 7.5942715274197585 0.01
Ball:
0.01 3.326678772481469 0.06596896184882373 2.2605788022466555 3.725067408388324 1.1346418651799477 0.01
Ball:
0.01 1.711603471110161 4.323586586186624 2.295297803592199 0.9165529136774072 0.525277330630739 0.01
Ball:
0.01 0.12321918664145848 0.5098671820399239 2.850818852082162 4.633080341302375 2.9599347131168887 0.01
Ball:
0.01 5.543529942710278 3.2658020337785088 1.945930553397914 3.202820353618595 5.598391995810349 0.01
Ball:
0.01 2.075060811416307 1.6256788559499054 1.5765356644216575 5.00736084873905 0.5987138676221733 0.01
Ball:
0.01 2.2723596709019325 0.6852177383071785 0.30290294934241846 0.1807667415252916 2.460193840108166 0.01
Ball:
0.01 1.6464453317153052 0.4652405092210636 1.6939359906669884 1.5941704380765676 2.3380868898804152 0.01
Ball:
0.01 3.3391714750518817 5.471360985136002 0.7430286358912759 1.896177578576474 3.298373359916601 0.01
Ball:
0.01 1.1255183127393384 1.5445507536841008 0.11056542846886566 5.886654738923316 1.2024169497620287 0.01
Ball:
0.01 0.7021142840104772 2.2699294229102973 1.2050866317737559 2.9344956976424545 2.7492029599868077 0.01
Ball:
0.01 4.274868687684214 0.13216112158767235 0.28697825889131146 2.0918233015463192 0.6206204844814083 0.01
Ball:
0.01 3.0328598546929566 2.0245930598802753 2.8795588053137884 2.850004822742411 2.1858481693918845 0.01
Ball:
0.01 0.007038680883717063 0.9783462837810526 0.3746613515404409 3.260440638103984 4.131560716355326 0.01
Ball:
0.01 1.0837240381290472 1.1164947284005304 1.9677305773103047 3.016348246649623 1.2718742347315215 0.01
Ball:
0.01 1.9735055516083735 2.776467743216687 0.49266225934832497 1.1988146998222304 3.210853533297154 0.01
Ball:
0.01 0.04664568333694663 1.514379092297335 2.903628564449867 3.750280019509392 1.0574341379038903 0.01
Ball:
0.01 0.7419657055990321 3.9383033929763362 3.6402773511942375 6.3226147991427535 0.7635264933139716 0.01
Ball:
0.01 3.164455476737242 3.8078021389655223 0.48588449299879455 4.315923739863284 1.1456330638891687 0.01
Ball:
0.01 1.033682033880301 0.3298081596495728 1.355306970620458 2.724644155608019 1.4526530254266086 0.01
Ball:
0.01 0.6946461919702972 0.5787347667921128 1.1219545827770836 5.937042629703578 0.5711517272626607 0.01
Ball:
0.01 0.992418427594562 2.0762741099258952 5.241966635465623 6.923984621173194 1.6129472477662947 0.01
Ball:
0.01 1.6228472947912638 1.4624399664001904 1.473760268472963 0.9846573588433835 4.272852463156281 0.01
Ball:
0.01 1.4882905908333077 2.9318132630470184 2.3842528017884517 0.12795497902359187 0.6364959783121031 0.01
Ball:
0.01 0.6880160057707485 3.6044654292754634 1.4661655436487917 1.2251836548888262 1.118114869012341 0.01
Ball:
0.01 0.829394275243147 0.5722485380277402 2.30453370366952 0.6584398716543902 1.553545380051313 0.01
Ball:
0.01 0.7626940823801058 2.3552887266802536 1.9515989010878758 1.0790643136732392 2.173660653354988 0.01
Ball:
0.01 2.560716920366686 2.828972397838737 3.4664712527827986 2.3181685615001255 5.2793572099556165 0.01
Ball:
0.01 1.814701962181165 5.667593766682918 0.23045444280381375 3.1869591766207064 3.792305208754363 0.01
Ball:
0.01 1.939781753119685 0.45951892509691916 1.3627655363376756 0.6829400798142884 2.8075814472306453 0.01
Ball:
0.01 0.12471740984855184 3.185165531198242 0.4730926768023352 2.8668119661804043 3.6634172771589735 0.01
Ball:
0.01 1.6896446536319516 0.916529493076625 3.7648328163586022 2.3430446942750836 1.538707154944314 0.01
Ball:
0.01 1.5561325297727406 4.697826090023569 0.5107316355079663 3.75368199881495 2.1062967091278395 0.01
Ball:
0.01 0.4696982500771498 1.000706887411189 3.291045334201828 3.1661912226046818 1.8474920059762105 0.01
Ball:
0.01 4.373938646926318 1.3672706695486272 2.1044605115679986 2.3661941293862006 2.0144580749953023 0.01
Ball:
0.01 0.7935695906442919 0.09681001723023375 0.7064874125664926 0.9905255014967126 0.6214016180731705 0.01
Ball:
0.01 0.173903918443452 0.7969954626047249 1.5733656851025422 1.6015874471854314 3.358069164538046 0.01
Ball:
0.01 4.406704477689866 2.3712400064850145 2.452684597346006 0.9871539911606086 1.8980466141999068 0.01
Ball:
0.01 2.3795915805078103 0.36405284796374615 1.135749376926008 3.5049169447740867 2.4394613312547424 0.01
Ball:
0.01 0.5022123451110312 7.768018910874193 5.787728579208233 1.0833893083067128 0.9098741522255273 0.01
Ball:
0.01 0.5641873205501233 5.429999597846677 1.8721314301341971 3.1447747382399704 1.7085161194981842 0.01
Ball:
0.01 4.239999139418121 0.44183936119492206 3.533499139977657 2.454492565468726 4.514572147930936 0.01
Ball:
0.01 1.5202900055722153 2.452805285069011 4.5204303994346855 1.6869391851901419 2.7265902488159743 0.01
Ball:
0.01 3.380517824413268 1.3336180306257952 0.3184094825956236 2.858590099286197 0.5670641317614165 0.01
Ball:
0.01 1.3144860660769018 1.6232763297588555 0.10109101958544231 1.4238304846887222 1.076212286683857 0.01
Ball:
0.01 3.731753977331409 6.869335352332744 3.3438807691938335 0.5054001859693481 1.1537614749870624 0.01
Ball:
0.01 2.2347059628336483 1.7154606145524296 1.236720848327185 0.8759528953477231 0.3903197845525558 0.01
Ball:
0.01 2.8685822354794697 0.25737969828620244 1.251463827383989 1.7206793783076373 3.2073025172271437 0.01
Ball:
0.01 0.6589719546229049 0.41969098582677367 1.8610730048495205 2.115572010545239 1.1493858462986708 0.01
Ball:
0.01 1.281722466819353 0.6471337268631745 0.11096553303830131 6.223821208198277 1.438932120942297 0.01
Ball:
0.01 2.8524046017441163 6.212749325701097 0.9208303780805508 2.2054311453157314 5.725322316029678 0.01
Ball:
0.01 2.1884614722765154 3.2352744667165374 2.1636788617475786 0.3320582026623604 0.8315608986944876 0.01
WideB:
0.5074745943574043 0.32670808692270104 0.047231059208361174 0.004737067804892643 0.07582300320126056 0.011109670599264009
Ball:
0.01 0.17049493334656285 1.3865443249624567 0.7383388297098082 1.0075292416739368 3.770942380980103 0.01
Ball:
0.01 0.7848551673253934 1.7689621169353082 1.3768117086507354 2.0730172268502436 0.09939419085494361 0.01
Ball:
0.01 1.7105109741097668 0.6182035710313916 2.1418907290705285 3.428500739984236 2.9890926720855195 0.01
Ball:
0.01 1.8011361289645844 0.3377592991120153 6.667015140769282 1.235103429362738 0.8246746184512512 0.01
Ball:
0.01 3.714770133412727 1.1960247358876723 2.9462708997180718 1.6654804221978956 1.7224215359348398 0.01
Ball:

0.01 0.5195348532171473 7.330525604945484 10.251512562434826 0.6143249908164234 1.9718817914549496 0.01
Ball:
0.01 1.489894517112684 0.5077109911550022 1.8230283456289005 1.9784459433838524 0.6037219273166279 0.01
Ball:
0.01 2.9696740122513923 1.0639454807965434 0.5346940588750203 2.5041568679842237 0.9063914454326905 0.01
Ball:
0.01 2.9005636845900673 1.242062827593084 5.9551467622755005 0.40061001900787674 5.533787341292234 0.01
Ball:
0.01 1.288801559563127 1.0824985266451892 0.350459935145948 1.8547036045599277 5.415519763652194 0.01
Ball:
0.01 1.6423944057678057 0.9213787930568446 0.7694628244087479 0.9096758875256774 2.2173123839089994 0.01
Ball:
0.01 1.8443844772004727 1.5227640809879253 1.407850979763405 1.1399042816102065 0.34672727349524557 0.01
Ball:
0.01 0.8175915283455439 0.7843878801090827 2.3606857298878077 0.22264992695867458 0.5550428162213651 0.01
Ball:
0.01 1.1918833766465882 1.1772903721715369 3.483775742100195 6.8703952144664155 3.2087118458044515 0.01
Ball:
0.01 0.22514087194275811 0.15990025379499562 3.736189227484002 1.3788510757825716 0.8486202739265798 0.01
Ball:
0.01 0.6362753480761434 3.5128277108701305 1.8106884900860198 1.229701120210245 0.46082164614381177 0.01
Ball:
0.01 1.493423156426816 1.4974986226461064 3.5516493811419814 0.4779486798441057 2.809017729026314 0.01
Ball:
0.01 0.983611521869833 6.763377896265391 4.207017543925708 1.6847716142073184 0.20627673464024499 0.01
Ball:
0.01 0.8856923763095512 3.3005156743396 2.885868465471554 1.8174923062078319 0.6323603398541144 0.01
Ball:
0.01 0.7594149875504915 0.41876648592895716 3.8297746558558274 2.561285146504239 3.2012646408940197 0.01
Ball:
0.01 1.0344168960491265 0.8887821664631317 2.6139864425678274 0.9628418764885518 0.8258786531621317 0.01
Ball:
0.01 0.12263798655902891 0.24512485874972123 3.8616257032501586 2.0539827468954464 0.6866388863735877 0.01
Ball:
0.01 7.271500682354695 3.4900474737460967 2.758655285484502 3.684974601826728 6.173161772251563 0.01
Ball:
0.01 0.2934047989768447 1.8992613006842873 0.045940290860850386 0.4930008357975085 2.8271953186837497 0.01
Ball:
0.01 3.970112815058834 1.3105407736222008 1.4206246818114152 3.430496059968103 0.3752812137560203 0.01
Ball:
0.01 0.3104328532003344 2.790565934327554 1.9929735042242458 2.1722618398467763 4.421672460323338 0.01
Ball:
0.01 1.6462387523514572 3.0957125750944985 1.2817844347262446 1.342938133532177 8.006287568662104 0.01
Ball:
0.01 0.5656852043600387 3.39781304187372 1.516683160047501 3.4040594237246573 2.4453351636834433 0.01
Ball:
0.01 3.0449619861175634 0.7079938997591227 2.4866149222583784 4.1706161470246075 0.31385678177958365 0.01
Ball:
0.01 0.9926762407363773 0.23437258986939136 3.810694828394058 0.8711257717161616 0.1088199565405577 0.01
Ball:
0.01 3.318093515675299 0.541899460977703 0.22895811835100327 2.2427512665530465 0.9561802128873991 0.01
Ball:
0.01 1.5897644628902277 3.6854239360330867 0.19824601614268414 0.07066611121575828 4.251237281120566 0.01
Ball:
0.01 2.566888341555778 1.1187764484321272 0.7636902687900137 4.138408791646392 3.755481939688864 0.01
Ball:
0.01 1.7988732711164008 0.41630423149665774 0.0950781479434406 2.400603540714937 4.195019638555567 0.01
Ball:
0.01 4.115460738975172 2.954892307935804 5.862183947801359 1.7946964297286008 0.7068748346034502 0.01
Ball:
0.01 2.9059811719328525 2.8647056781858202 2.574904580095537 2.6773077071771785 0.9985735565267868 0.01
Ball:
0.01 1.8745991784526583 1.9198059235096803 0.5298131835691281 0.7774892301621694 0.5872912642322299 0.01
Ball:
0.01 0.27626634831991426 0.8630195988640406 0.9620568880749802 0.025284048531882153 0.26877793709473924 0.01
Ball:
0.01 0.35977896795581454 1.8296827510117684 0.539623936083619 1.9107282579281724 0.26123914008444205 0.01
Ball:
0.01 0.6437477399549735 0.832927156824119 2.1642668944690864 1.3963237788192928 1.27487270399629 0.01
Ball:
0.01 2.02650496254261 0.5938326905979774 0.9058071648466848 5.066477147211731 1.318912395212204 0.01
Ball:
0.01 2.3761023565686585 0.28492506081832314 2.037232661410358 0.36841881017742395 4.4532107029016785 0.01
Ball:
0.01 0.3791009980589497 2.3383696224223107 3.1197229886860445 2.058557560574748 1.528438003085549 0.01
Ball:
0.01 3.3405735446967313 1.0801418387524806 0.21374651208519546 1.5609844132936002 0.2908118576460803 0.01
Ball:
0.01 2.755608117761304 3.8357860769086956 0.5637642001989271 1.8156986150644185 3.6183750183337318 0.01
Ball:
0.01 1.6145845568267094 3.6675766851996663 1.4131488872506786 0.13913038945319467 2.8442607335842194 0.01
Ball:
0.01 6.076334534204161 1.7567282772736974 0.6381544608484611 1.1002718217751082 2.266370898946267 0.01
Ball:
0.01 1.3278751581876755 0.7489948653428958 3.607993491417255 1.3062627926091888 1.5757970151025722 0.01
Ball:
0.01 0.7509692369873582 0.2988318269263204 3.1268990896531332 1.604424987151818 0.3022095011995125 0.01
Ball:
0.01 1.107892784148126 1.1945839297108385 0.3941340610817018 1.0873197864408826 0.17437809466646695 0.01
Ball:
0.01 2.5785381208046205 2.242476182832373 1.634996772379461 0.003160343173557817 0.6092391262379497 0.01
Ball:
0.01 4.848535819079324 0.4251229674309793 3.4625321736708496 0.3345345451046624 0.06815533947715169 0.01
WideB:
0.5074745943574043 0.32670808692270104 0.047231059208361174 0.004737067804892643 0.07582300320126056 0.011109670599264009
Ball:
0.01 0.5945993417129262 3.4404502051636716 3.9357907486881407 3.2376105356321085 4.288484414109339 0.01
Ball:
0.01 3.373991122548671 2.93915739996536 0.10742932791757001 0.4974784167624964 3.3210522643516436 0.01
Ball:
0.01 0.8014373704679416 1.3771295963750076 1.6689639656600994 0.4191083727650524 3.9660873118913624 0.01
Ball:
0.01 4.26133748350271 0.09802117651489278 0.7315097802012737 1.3965060273491858 1.384654241654709 0.01
Ball:
0.01 1.9702462654198718 0.7045587672666579 2.5991838111044 0.0727908352053922 2.5832128230406513 0.01
Ball:
0.01 1.9419324272071918 1.0027694309241573 1.8955923474559688 1.3548118542700966 3.299705551325298 0.01
Ball:
0.01 1.0596015106764614 2.7771095780037642 3.605357311112332 0.9554258016052469 2.1271866786231537 0.01
Ball:
0.01 0.11577882012292395 0.23057173018441013 3.1334652705186605 2.8327420606856566 0.6333769166642758 0.01
Ball:
0.01 2.0582151670516264 3.4154006599612527 1.1310451470570693 0.18091986144358496 2.2376164363284663 0.01
Ball:
0.01 0.6370022886604794 2.049889406562463 0.7473774944482457 4.294063436981019 0.7632191393713614 0.01
Ball:
0.01 2.03945685290956 0.7010951118029135 5.319813737814185 0.10426117665475883 0.0211963729809852 0.01
Ball:
0.01 2.3671308650556284 0.9194287844221319 0.32568024592597355 1.1805850052648683 0.7066598538504695 0.01
Ball:
0.01 0.371793088303083 1.8942133574479212 1.5823576483755 0.40744561107090416 1.3967366030159487 0.01
Ball:
0.01 1.6130117324320126 2.6579800580597692 1.6988864629547893 1.0978386457930913 3.398292995929851 0.01
Ball:
0.01 0.44009743989327266 1.411851056366487 3.4440668724219394 0.45951839590856924 10.415187226233233 0.01
Ball:
0.01 2.773112049181411 4.579016896642326 3.269282612561245 0.7514610849264036 5.960489203898717 0.01
Ball:
0.01 0.6779072639193373 3.5345676462791964 0.03612101431413506 1.2689621679743563 0.5264693819957754 0.01
Ball:
0.01 0.9259791239685655 1.2216112155317107 4.014537639896842 3.033376284575442 1.5488671340516933 0.01
Ball:
0.01 0.625701507953877 1.8380810762090432 0.9924057694039018 0.30341237695358303 1.5423006583172412 0.01
Ball:
0.01 2.0769253222810526 0.6764143320951557 2.3917112625383066 0.9736208681236269 0.21198914826275606 0.01
Ball:
0.01 0.5106522199027759 1.5616522208192753 2.3617036532686506 4.368890641155412 3.6595880119396362 0.01
Ball:
0.01 0.7706802276956365 2.5565189550217253 0.7490224648113231 2.3475414802744106 0.626096441475498 0.01
Ball:
0.01 0.09991879052956287 1.2911342616871173 0.37896924371180085 0.774200317680179 4.062072676398883 0.01
Ball:
0.01 2.3830087428873865 1.3936232501970967 2.1355976066237945 2.7849001207736754 1.1005351166587816 0.01
Ball:
0.01 3.876653112661367 2.16705370328723 3.054074411651486 1.2894709828992075 2.9289668675520906 0.01
Ball:
0.01 4.243520079247104 0.050391393534869766 2.088251770830849 2.4767693878283823 1.4653355301362954 0.01
Ball:
0.01 2.5759600549717585 0.972605496558933 1.0471201688525351 1.4135939300605966 0.9057050129082495 0.01
WideB:
0.5074745943574043 0.32670808692270104 0.047231059208361174 0.004737067804892643 0.07582300320126056 0.011109670599264009
Ball:
0.01 1.753084784902204 2.700766785038656 2.0107413720416503 1.0465827425461312 0.23043150219082587 0.01
Ball:
0.01 2.460869835567072 2.8073281476907335 0.5160661986783941 2.821878358949071 2.393993727832445 0.01
Ball:
0.01 2.3538578962389503 0.23897681924191405 2.0917120043490076 0.9682744988507148 0.7443181763167153 0.01
Ball:
0.01 0.11291255360404623 3.9354346215372553 1.7675027379997161 1.3230190902071477 2.0883646358436683 0.01
Ball:
0.01 0.9626764930603546 4.002294648130354 0.2519275954792073 0.865514861055011 2.572540491137177 0.01
Ball:
0.01 0.3065572105979164 1.5194428797473674 2.7489554730169896 1.7527857082765474 1.4243534302561014 0.01
Ball:
0.01 2.0492114786691324 1.65824699461833 2.559826541926056 3.0329220775826777 3.6880498248369054 0.01
Ball:
0.01 1.6496037512559139 1.8874651425023141 0.5537792900962285 4.015602622456173 5.008627605690718 0.01
Ball:
0.01 1.3583211889695503 0.344457258169007 0.5667523004225219 0.7282682773432199 0.6887633679521299 0.01
Ball:
0.01 2.1799239821889898 1.8308681477395106 2.6168231427329047 5.837068295889189 0.33728124267232373 0.01
Ball:
0.01 2.8024662794126174 4.521492969328356 1.390221064953535 2.0731737571525164 3.757131853704936 0.01
Ball:
0.01 0.27420794962497475 0.9484535590800703 3.578173030935073 0.9229583861309661 2.8593971839067853 0.01
Ball:
0.01 1.5575859870183273 0.8890835862343351 1.2831630027483438 1.3894669864114282 6.715260811085746 0.01
Ball:
0.01 3.3204913171632215 3.6308183346948506 1.0215582974399586 2.115462951084379 1.4824692219830111 0.01
Ball:
0.01 1.9180081958050947 0.13092188399608196 2.661491167357503 0.0802789594238606 0.7626789454191358 0.01
Ball:
0.01 6.046008078074562 1.5225526622026924 0.19254411054937126 3.4389743786412157 2.4905321071868762 0.01
Ball:
0.01 1.4127975822683565 4.351747899238302 0.9090985082989257 1.1879715823861412 1.5383755732896676 0.01
Ball:
0.01 1.712045775073547 1.224353419616907 1.501638936743825 1.9477246980389533 3.0993098573617104 0.01
Ball:
0.01 3.848677066602244 0.7771105310190781 0.913912100725038 0.5004347361389874 3.2081630614090835 0.01
Ball:
0.01 0.6420105220551087 3.864483379597407 4.104977714265869 2.3122265386964185 0.9725365513246325 0.01
Ball:
0.01 1.5913577515292459 2.9615481355873867 0.5986014237472397 0.49124650854625346 1.4191503767098046 0.01
Ball:
0.01 3.2578368346048494 0.06253689133657703 2.888375973181467 1.724865417177165 2.0683999194924088 0.01
Ball:
0.01 4.437442661037872 2.35886504781037 0.39402191067862163 0.5303891504295235 0.4735350762021435 0.01
Ball:
0.01 1.235790226007941 1.2192599543436056 0.6309424450920347 0.8004376130667366 3.760190926783774 0.01
Ball:
0.01 0.39180871600581524 1.577231482031391 2.3110431674633936 0.10107747432747471 2.4644671737735795 0.01
Ball:
0.01 1.988247005702458 6.118792032893577 3.991768142060464 0.4282259499955887 2.7807567956113886 0.01
Ball:
0.01 3.2105768339755305 3.9634404690659957 1.373105496890015 3.2912642682693383 0.24090615314592378 0.01
WideB:
0.5074745943574043 0.32670808692270104 0.047231059208361174 0.004737067804892643 0.07582300320126056 0.011109670599264009
Ball:
0.01 2.134571721137428 0.5891739784261207 2.4758494667789717 3.26578334276689 2.112697372744988 0.01
Ball:
0.01 3.2253585716973445 1.5357569137659985 8.208154044208712 1.636644788021337 2.9413343355986843 0.01
Ball:
0.01 0.9894988146071807 2.83835436331255 0.7324579703235379 2.1897689398945794 3.9283679907551328 0.01
Ball:
0.01 0.5874212070867031 0.0021271509056512983 1.6078006826125193 3.41844260584421 1.9893397314466348 0.01
Ball:
0.01 0.8018367503484609 1.8590786719713748 0.5392888395992286 0.5396069572999691 1.70051461942337 0.01
Ball:
0.01 0.04177050780986469 1.4894068631612822 2.174145672892296 2.9938709445828344 2.9722010963056347 0.01
Ball:
0.01 1.6206372953429766 0.7946863265557087 1.5392817716488194 4.90456481344977 2.2750414902116356 0.01
Ball:
0.01 0.5910514238305922 4.434165766106415 2.4581277148614555 0.04161447638385801 4.984071042558965 0.01
Ball:
0.01 0.24584447401511683 0.18803700107549948 0.8052361233812401 2.0305973444294367 0.5230147504324939 0.01
Ball:
0.01 0.42121698396226204 0.38430093627045964 0.507526872646832 1.5068353192471098 2.6192033314150946 0.01
Ball:
0.01 0.366440173358088 7.906018406865421 1.727232921343757 0.5142544212645683 1.9809900879588735 0.01
Ball:
0.01 1.2916685929823428 2.0132326799793026 0.6606752444697177 1.614240758459266 0.9126698056997564 0.01
Ball:
0.01 3.9099590667878115 0.7660842567217259 5.731452902498891 3.936334538697288 0.9963440220170827 0.01
Ball:
0.01 1.5255252681049134 0.8276369251009086 1.3491265670364803 1.3072631287573029 5.6664804701052764 0.01
Ball:
0.01 3.103736318542198 1.3250478702354995 1.676935093138739 4.447094773419039 0.30114732752796963 0.01
Ball:
0.01 5.260205038152501 1.9360089221121743 1.7288603812529932 3.234927972094323 2.2613296668670544 0.01
Ball:
0.01 3.9639818434234684 0.15989481245617032 0.044051206208993055 1.4327783880018115 3.8101411388478867 0.01
Ball:
0.01 3.2360710579875445 2.2517318554118977 1.2184063978904693 4.463164597720182 0.8254204364485374 0.01
Ball:
0.01 4.669767915732169 0.02593435246448972 0.24679143132334758 2.0429579840636345 6.175643719391879 0.01
Ball:
0.01 4.185498237397552 4.118459239943515 2.157754488636449 2.252999008306122 9.899381577559964 0.01
Ball:
0.01 7.777275905701714 1.075183137767816 1.1648319654573485 1.3451458696764926 2.948831725654088 0.01
Ball:
0.01 0.7701235293720776 1.519058004617197 3.1538215723794973 1.8936613249928582 0.672020425180551 0.01
Ball:
0.01 2.263248362778013 3.1965434071973298 4.226981108683841 0.49614756126548326 0.5338722313060731 0.01
Ball:
0.01 2.245483841223308 3.6304016312264227 1.3178207244778717 0.341333822146478 1.344935783401501 0.01
Ball:
0.01 0.20306269574243818 2.863802417808675 1.3731212990848733 0.1595609393731217 1.456696562302693 0.01
Ball:

0.01 6.528394517402223 2.201941621506352 0.7801728539766154 1.8934689177749866 0.7389595593876324 0.01
Ball:
0.01 7.043432721906155 1.5815526432370843 3.1409844485097116 0.3170645009641738 2.7711527053222103 0.01
WideB:
0.5074745943574043 0.32670808692270104 0.047231059208361174 0.004737067804892643 0.07582300320126056 0.011109670599264009
Ball:
0.01 1.5838540319424537 1.1644143805688243 0.01571504218080033 3.0307781552411823 0.3701114310525314 0.01
Ball:
0.01 2.168429892211034 4.660724439337665 3.2618092948707664 4.020204115673376 2.168259209426494 0.01
Ball:
0.01 0.5623435623212101 0.891104601478302 1.2726936450684956 2.1468986179226226 2.9453979708919475 0.01
Ball:
0.01 1.1962034866713525 1.9619687812750444 1.204674908552029 1.3910410763362346 1.1042216814408319 0.01
Ball:
0.01 1.5881413871013197 0.5742601743702593 1.2029738361210514 2.445604323175412 1.8788914906039504 0.01
Ball:
0.01 2.006178225522204 0.7461182799320222 0.8196141030746367 0.6678288049985948 8.056157713285485 0.01
Ball:
0.01 6.0616601333805935 0.6077637879118355 5.128650046954928 0.9146256338464536 2.9311073319924295 0.01
Ball:
0.01 0.2718946604485812 1.0932692714687988 0.4192088508426256 4.8786203793982335 0.013878235422414398 0.01